version: '3.7'

x-minio-common: &minio-common
  image: quay.io/minio/minio:latest
  command: server --console-address ":9090" /mnt/data
  environment:
    MINIO_ROOT_USER: minio
    MINIO_ROOT_PASSWORD: minio123
  #   MINIO_REGION_NAME: us-east-1
  #   MINIO_BROWSER: off
  #   MINIO_UPDATE: off
  #   MINIO_ACCESS_KEY: minio
  #   MINIO_SECRET_KEY: minio123
  ports:
    - "9000:9000"
    - "9090:9090"

services:
  minio1:
    <<: *minio-common
    hostname: minio1
    volumes:
      - ./etc/default/minio:/etc/config.env
      - ./mnt/data/compose:/mnt/data

